WebApp/backend/controllers/ApiController.php
<?php
namespace backend\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\ExtractedDataNozzle;
use yii\web\Response;

/**
 * Site controller
 */
class ApiController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','failuretotal', 'stationsummary', 'predictionreport', 'predictionreportbystation'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action) {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        echo 'Salom';
    }


    public function actionFailuretotal()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        //id, case_id, station_id, business_partner_name, pump, gas_type, creation_date, completion_date, days_to_action, lifetime,
        // transaction_days, transaction_count, adjusted_transaction_count, total_volume, adjusted_total_volume

        $model = (new \yii\db\Query())
            ->select('station_id, COUNT(*) as num_failure')
            ->from('extracted_data_nozzle')
            //->where(['gas_type' => '95'])
            ->where(['>', 'lifetime', 0])
            ->groupBy(['station_id'])
            ->all();

        $my_data=[];
        foreach ($model as $key => $value) {
            $my_data['station_id'][$key] =$value['station_id'];
            $my_data['num_failure'][$key] =$value['num_failure'];
        }

        //$data=array_map(create_function('$m','return $m->getAttributes(array(\'pump\',\'lifetime\'));'),$my_data);

        echo json_encode($my_data);
    }

    public function actionStationsummary()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $station_id=$_POST['station_id'];
        $gas_type=$_POST['gas_type'];
//        SELECT e.pump, e.lifetime, p.lifetime_predicted
//        FROM extracted_data_nozzle e
//        left join data_nozzle_predicted as p on p.related_id=e.id
//        where e.lifetime>0 and station_id='RYB0715'
//        order by e.pump

        $model = (new \yii\db\Query())
            ->select('e.pump, e.lifetime, p.lifetime_predicted')
            ->from('extracted_data_nozzle as e')
            ->leftJoin('data_nozzle_predicted as p', 'p.related_id=e.id')
            ->where(['>', 'lifetime', 0])
            ->andWhere(['=', 'e.station_id', $station_id])
            ->andWhere(['=', 'e.gas_type', $gas_type])
            ->groupBy(['e.pump'])
            ->all();

        $my_data=[];
        foreach ($model as $key => $value) {
            $my_data['pump'][$key] =$value['pump'];
            $my_data['lifetime'][$key] =$value['lifetime'];
            $my_data['lifetime_predicted'][$key] =$value['lifetime_predicted'];
        }

        //$data=array_map(create_function('$m','return $m->getAttributes(array(\'pump\',\'lifetime\'));'),$my_data);

        echo json_encode($my_data);
    }


// To generate prediction report on predictions/index.php
    public function actionPredictionreport()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        //id, case_id, station_id, business_partner_name, pump, gas_type, creation_date, completion_date, days_to_action, lifetime,
        // transaction_days, transaction_count, adjusted_transaction_count, total_volume, adjusted_total_volume

        $model = (new \yii\db\Query())
            ->select('a.id, a.business_partner_name, a.pump, a.gas_type, b.lifetime_predicted, a.completion_date')
            ->from('extracted_data_nozzle as a')
            ->leftJoin('data_nozzle_predicted as b', 'b.related_id=a.id')
            //->where(['gas_type' => '95'])
            ->where(['>', 'lifetime', 0])
            // ->groupBy(['a.business_partner_name'])
            ->all();

        // $object=NULL;
        $my_data=[];
        foreach ($model as $key => $value) {

            $my_data['data'][$key]['id']=$value['id'];
            $my_data['data'][$key]['business_partner_name']=$value['business_partner_name'];
            $my_data['data'][$key]['pump']=$value['pump'];
            $my_data['data'][$key]['gas_type']=$value['gas_type'];
            $my_data['data'][$key]['lifetime_predicted']=$value['lifetime_predicted'];
            $my_data['data'][$key]['completion_date']=$value['completion_date'];
        }



        //$data=array_map(create_function('$m','return $m->getAttributes(array(\'pump\',\'lifetime\'));'),$my_data);

        echo json_encode($my_data);
        // echo json_encode($my_data);
    }

    // To generate prediction report on predictions/index.php
    public function actionPredictionreportbystation()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $station_id=$_POST['station_id'];
        $gas_type=$_POST['gas_type'];

            $model = (new \yii\db\Query())
            ->select('a.id, a.business_partner_name, a.pump, a.gas_type, b.lifetime_predicted, a.station_id, a.gas_type, a.completion_date')
            ->from('extracted_data_nozzle as a')
            ->leftJoin('data_nozzle_predicted as b', 'b.related_id=a.id')
            //->where(['gas_type' => '95'])
            ->where(['>', 'lifetime', 0])
            ->andWhere(['=', 'a.station_id', $station_id])
            ->andWhere(['=', 'a.gas_type', $gas_type])
            // ->groupBy(['a.business_partner_name'])
            ->all();

        // $gas_type="95";
        // $station_id="RYB0715";
        //id, case_id, station_id, business_partner_name, pump, gas_type, creation_date, completion_date, days_to_action, lifetime,
        // transaction_days, transaction_count, adjusted_transaction_count, total_volume, adjusted_total_volume

        // $object=NULL;
        $my_data=[];
        foreach ($model as $key => $value) {

            $my_data['data'][$key]['id']=$value['id'];
            $my_data['data'][$key]['business_partner_name']=$value['business_partner_name'];
            $my_data['data'][$key]['pump']=$value['pump'];
            $my_data['data'][$key]['gas_type']=$value['gas_type'];
            $my_data['data'][$key]['lifetime_predicted']=$value['lifetime_predicted'];
            $my_data['data'][$key]['completion_date']=$value['completion_date'];
        }



        //$data=array_map(create_function('$m','return $m->getAttributes(array(\'pump\',\'lifetime\'));'),$my_data);

        echo json_encode($my_data);
        // echo json_encode($my_data);
    }




}

WebApp/backend/controllers/PredictionsController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class PredictionsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }


}

WebApp/backend/views/predictions/index.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 11/9/2017
 * Time: 7:30 PM
 */

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'DASHBOARD | GTD PREDICTIVE ANALYSIS';
?>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<table id="predictions-report" class="display table table-striped b-t b-b" style="width:100%">
        <thead>
            <tr>
                <th>Business Partner Name</th>
                <th>Pump</th>
                <th>Equipment</th>
                <th>Gas Type</th>
                <th>Completion Date</th>
                <th>Lifetime Prediction</th>
                <th>Expected Failure</th>
                <th>Remaining Expected Life</th>

            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Business Partner Name</th>
                <th>Pump</th>
                <th>Equipment</th>
                <th>Gas Type</th>
                <th>Completion Date</th>
                <th>Lifetime Prediction</th>
                <th>Expected Failure</th>
                <th>Remaining Expected Life</th>

            </tr>
        </tfoot>
</table>


    <script type="text/javascript">

        var todayDate = moment();

    	$(document).ready(function() {
    prediction_table = $('#predictions-report').DataTable( {
	        "ajax": {
	        	"url":"<?= Url::to(['/api/predictionreport']); ?>",
	        	"dataSrc": function ( json ) {
			      for ( var i=0, ien=json.data.length ; i<ien ; i++ ) {
			        // json.data[i][] = 'huehuehue';
			        json.data[i].business_partner_name = json.data[i].business_partner_name;
			        json.data[i].pump = json.data[i].pump;
			        json.data[i].equipment = "Nozzle";
			        json.data[i].gas_type = json.data[i].gas_type;
                    var predict_days = json.data[i].lifetime_predicted;
                    //get last corrective maintenance date, add predict_day into to get failure date
                    var expected_failure = moment(json.data[i].completion_date, "YYYY-MM-DD").add(predict_days, 'days').format("DD/MM/YYYY"); 
                    var completion_date = moment(json.data[i].completion_date, "YYYY-MM-DD").format("DD/MM/YYYY");
                    var label = "green";
                    var todayDate = moment();

                    var remaining_life = moment(expected_failure,"DD/MM/YYYY").diff(todayDate, 'days');


                    if(remaining_life <= 7){
                        label = "red";
                    }else if(remaining_life <= 30){
                        label = "warn";
                    }else{
                        label = "green";
                    }

                    remaining_life = "<span class='label "+label+"'>"+remaining_life+"</span>"; // to add styling inside the table
                    json.data[i].remaining_life = remaining_life;
                    json.data[i].lifetime_predicted = predict_days;
                    json.data[i].expected_failure = expected_failure;
                    json.data[i].completion_date = completion_date;

			        // console.log("AJAX MODIFY TABLE");
			        // console.log("Current data : "+json.data[i].business_partner_name);
			      }
			      return json.data;
			    }
	        },
	        "processing": true,
	        "columns": [
	            { "data": "business_partner_name" },
	            { "data": "pump" },
	            { "data": "equipment" },
	            { "data": "gas_type" },
                { "data": "completion_date" },
	            { "data": "lifetime_predicted" },
                { "data": "expected_failure" },
                { "data": "remaining_life" }
	        ]
	    } );
	} );


    	// To insert more row of data into datatable
    	// var equipments = [];
    	// equipments.push("Nozzle");

    	// prediction_table.row.add(equipments);
    	// prediction_table.draw();

    </script>